parser: '@typescript-eslint/parser'

extends:
  - plugin:@typescript-eslint/recommended
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: ./tsconfig.json

rules:
  '@typescript-eslint/semi':
    - error
    - never
  '@typescript-eslint/no-explicit-any':
    - off
    - never
  '@typescript-eslint/interface-name-prefix':
    - warn
    - always
  '@typescript-eslint/no-use-before-define':
    - off
    - never

